config/routes.rb
Firehose::Application.routes.draw do

  
  root :to => "b_bproducts#blank"

  resources :futureshop, only: [:index, :show], id: /\w+/i
  resources :bestbuy, only: [:index, :show], id: /\w+/i
  resources :accessories, only: [:index, :show], id: /\w+/i

  resources :product_types, path: "/", id: /[BFA]\w+/i, only: [:show] do
    resources :facets, only: [:index, :new, :create, :edit, :update], id: /\w+/, path: "layout_editor"
    resources :scraping_corrections, :except => [:show, :index], id: /\d+/
    resources :scraping_rules, id: /[\d-]+/
    resources :b_bproducts, only: [:index, :show], id: /\w+/
    resources :category_id_product_type_maps, only: [:new], :path=>"category_ids"
    match "category_ids" => "category_id_product_type_maps#show"
    match "scraping_rules/raisepriority" => "scraping_rules#raisepriority"
    match "/" => "b_bproducts#blank"
  end
  
  
end

app/models/scraping_rule.rb
class ScrapingRule < ActiveRecord::Base
  #Validation for remote_featurename, local_featurename
  validates :local_featurename,  :presence => true, :format => { :with => /^(\w|_)+$/}
  validates :remote_featurename, :presence => true
  validates :regex, :presence => true
  validates :product_type, :presence => true
  validates :rule_type, :presence => true
  validates :bilingual, :inclusion => { :in => [false] }, :unless => "rule_type == 'Categorical'"
  has_many :candidates
  has_many :scraping_corrections

  REGEXES = {"any" => ".*", "price" => "\d*(\.\d+)?", "imgsurl" => '^(.*)/http://www.bestbuy.ca\1', "imgmurl" => '^(.*)55x55(.*)/http://www.bestbuy.ca\1100x100\2', 'imglurl' => '^(.*)55x55(.*)/http://www.bestbuy.ca\1100x100\2', 'Not Avaliable' =>'(Information Not Available)|(Not Applicable)/0' }
  
  # Get list of candidate scraping rules to be applied for specified array of BBproduct instances.
  # Also gathers translations for categorical feature attributes.
  #
  # bb_products - Array of BBproduct instances.
  # ret_raw - Should we return raw data for debugging purposes?
  # rules - Rules to be applied. If empty, rules for the category will be retrieved from the database.
  # multi - Should we process local features with multiple rules? 
  #           true: process only local features with multiple rules.
  #           false: process only local features with a single rule.
  #           nil: process all local features, regardless of rule cardinality.
  # to_show - If true, disable translation gathering.
  #
  # Returns hash of {:translations, :candidates, :raw}.
  #   - translations: Array of arrays of form ['en'/'fr', key, parsed]. Key has form
  #                   "cat_option.<retailer>.<local feature name>.<English version of parsed value>". Duplicate entries may be returned.
  #                   It is also possible for multiple French translations to be returned with the same key.
  #   - candidates: Candidate scraping rules to be applied for the products provided. Multiple candidates may be returned for the same local 
  #                 feature, the decision about which candidate to apply in such cases is made later.
  #   - raw: If ret_raw is true, contains raw data returned by BestBuy API for the *first* product in the list provided.
  def self.scrape(bb_products, ret_raw = false, rules = [], multi = nil, to_show = false)
    bb_products = Array(bb_products)

    retailer_infos = []

    bb_products.each do |bb_product|
      sku = bb_product.id

      english_info = BestBuyApi.get_product_info(sku, true)
      english_info["category_id"] = bb_product.category unless english_info.nil?

      french_info = BestBuyApi.get_product_info(sku, false)
      french_info["category_id"] = bb_product.category unless french_info.nil?

      retailer_infos << RetailerProductInfo.new(sku, english_info, french_info)
    end

    apply_rules(retailer_infos, ret_raw, rules, multi, to_show)
  end

  # Get list of candidate scraping rules to be applied for specified array of product info hashes.
  # Also gathers translations for categorical feature attributes.
  #
  # product_infos - Array of RetailerProductInfo objects.
  #
  # For other arguments and return value, see documentation for scrape(), above.
  def self.apply_rules(product_infos, ret_raw = false, rules = [], multi = nil, to_show = false)
    candidates = []
    translations = []
    
    rules_hash = get_rules(rules,multi)

    if rules_hash.empty?
      return {translations: translations, candidates: candidates}
    end

    corrections = ScrapingCorrection.all
    product_infos.each do |product_info|
      raw_return = nil
      # We acquire translations of feature values for each product, duplicates are filtered later.
      en_trans = {}
      fr_trans = {}
      # For each product, we query both English and French product information.
      [:english, :french].each do |language|
        is_english = (language == :english)

        raw_info = product_info.get_info(language)

        unless raw_info.nil?
          rules_hash.each do |r|
            next unless (!r[:rule].french && is_english) || (r[:rule].french && !is_english)
            #Traverse the hash hierarchy
            if r[:specs]
              if raw_info["specs"]
                raw = raw_info["specs"].find do |spec|
                  spec["group"] == r[:specs][:group] && spec["name"] == r[:specs][:name]
                end
                raw = raw["value"] unless raw.nil?
              end
            else
              raw = raw_info[r[:rule].remote_featurename]
            end
            corr = corrections.find{|c|c.product_id == product_info.sku && c.scraping_rule_id == r[:rule].id && (c.raw == raw.to_s || c.raw == Digest::MD5.hexdigest(raw.to_s))}
            if corr
              parsed = corr.corrected
              delinquent = false
            else
              #We can handle multiple passes of regular expressions with ^^
              current_text = raw.to_s
              parsed = nil
              r[:regex].each do |current_regex|
                begin
                  if current_regex[:sub]
                    #Replacement part of the regex (do a match first, since it's a two-part operation)
                    parsed_temp = current_text[current_regex[:reg]]
                    parsed_temp = parsed_temp.sub(current_regex[:reg],current_regex[:sub]) if parsed_temp
                  else
                    #Just match, not replacement
                    parsed_temp = current_text[current_regex[:reg]]
                  end
                rescue RegexpError
                  parsed_temp = "**Regex Error"
                end
                # If match was successful, continue on from loop
                unless parsed_temp.nil?
                  parsed = parsed_temp
                  break
                end
              end
              
              #Validation Tests
              parsed = "**LOW" if r[:rule].min && parsed && parsed.to_f < r[:rule].min
              parsed = "**HIGH" if r[:rule].max && parsed && parsed.to_f > r[:rule].max
              parsed = "**INVALID" if r[:rule].rule_type == "Categorical" && parsed && !r[:rule].valid_inputs.blank? && !r[:rule].valid_inputs.split("*").include?(parsed)
              
              delinquent = parsed.blank? || (parsed == "**LOW") || (parsed == "**HIGH") || (parsed == "**Regex Error") || (parsed == "**INVALID")
            end

            unless to_show || r[:rule].rule_type != "Categorical" #Only translate categorical features
              local_featurename = r[:rule].local_featurename
              trans = r[:rule].french ? fr_trans : en_trans
              # Store the translation and if it's already there only store the highest priority match
              if !delinquent && (!trans.has_key?(local_featurename) || r[:rule].priority < trans[local_featurename][1])
                trans[local_featurename] = [parsed, r[:rule].priority]
              end
            end
            if !(r[:rule].bilingual && !to_show && r[:rule].french) #Don't save data twice, so don't save it for french
              # Save the new candidate - if multi is true, we may save multiple candidates for the same local feature.
              # We will choose the one that actually gets applied later.
              candidates << Candidate.new(
                parsed: (r[:rule].local_featurename == "product_type" || r[:rule].rule_type != "Categorical" ? parsed : (parsed.nil? ? nil : CGI::escape(parsed.downcase))),
                raw: raw.to_s,
                scraping_rule_id: r[:rule].id,
                sku: product_info.sku,
                delinquent: delinquent,
                scraping_correction_id: (corr ? corr.id : nil),
                model: r[:rule].rule_type,
                name: r[:rule].local_featurename
              )
              #Note: we really should take product_type out of scraping_rules and hard code it
            end
          end
          #Return the raw info only on the first pass
          raw_return = raw_info if is_english && ret_raw == true 
          if !is_english && ret_raw == true
            raw_return["French Specs"] = raw_info["specs"]
            ret_raw = raw_return
          end
        end
      end
      if en_trans.empty?
        Rails.logger.debug "No english translations found for product #{product_info.sku}. Please ensure each scraping rule needing a translation has an english version." unless to_show
      else
        en_trans.each_pair do |lf, data|
          parsed = data.first
          key = "cat_option.#{Session.retailer}.#{lf}.#{CGI::escape(parsed.gsub('.','-').downcase)}"
          translations << ['en', key, parsed]
          begin
            unless fr_trans[lf].nil? # Don't save a french translation if nothing is scraped
              translations << ['fr', key, fr_trans[lf][0]]
            end
          rescue
            puts "A french translation may have not been defined for product #{product_info.sku} #{lf}, or its value is missing"
          end
        end
      end
    end
    {translations: translations, candidates: candidates, raw: ret_raw}
  end
  
  def self.get_rules(rules, multi)
    # return rules with the regexp objects
    rules_hash = []
    rules = [rules] unless rules.class == Array #Create an array if necessary
    rules = ScrapingRule.find_all_by_product_type(Session.product_type_path) if rules.empty?
    #Multi can be nil, true, or false
    # If nil, it will be ignored
    # If true it will only return candidates from multiple remote_featurenames for one local_featurename
    # If false it will only return candidates from local_featurenames with one remote_featurename
    unless multi.nil?
      groups = rules.group_by(&:local_featurename)
      rules = []
      groups.each_pair do |lf, grouped_rules|
        rules += grouped_rules if multi && grouped_rules.length > 1
        rules += grouped_rules if !multi && grouped_rules.length == 1
      end

app/controllers/scraping_rules_controller.rb
class ScrapingRulesController < ApplicationController
  layout false, except: :index
  
  def index
    @rules = ScrapingRule.order('priority').find_all_by_product_type(params[:full] ? Session.product_type_path : Session.product_type).group_by(&:local_featurename)
    @colors = {}
    @rules.each_pair do |lf, rs|
      @colors.merge! Hash[*rs.map(&:id).zip(%w(#4F3333 green blue purple pink yellow orange brown black)).flatten]
    end
    #Calculate Coverage
    
    if params[:coverage] || params[:full]
      @coverage = {}
      products = params[:full] ? BestBuyApi.category_ids(Session.product_type) : BestBuyApi.some_ids(Session.product_type)
      @products_count = products.count
      ScrapingRule.scrape(products,false,[],nil,true)[:candidates].group_by{|c|c.scraping_rule.local_featurename}.each_pair do |lf, candidates| 
        groups = candidates.group_by(&:scraping_rule_id)
        if groups.keys.length > 1
          @coverage[lf] = covered(Candidate.multi(candidates))
        end
        groups.each_pair{|sr_id, candidates| @coverage[sr_id] = covered(candidates)}
      end
    end
  end
  
  def new
    @raw = params[:raw]
    #Fix utf-8 encoding
    params[:rule][:remote_featurename] = CGI::unescape(params[:rule][:remote_featurename]) if params[:rule] && params[:rule][:remote_featurename] 
    @scraping_rule = ScrapingRule.new(params[:rule])
  end
  
  def edit
    @scraping_rule = ScrapingRule.find(params[:id])
  end

  def raisepriority
    # The basic algorithm is this: Find the given rule. Swap priorities with the rule that's one lower.
    rule = ScrapingRule.find(params[:id])
    if rule.priority > 0 # If the rule priority number is 0, its priority can't be raised higher
      other_rules = ScrapingRule.where("priority < ?", rule.priority).find_all_by_local_featurename_and_product_type(rule.local_featurename, rule.product_type)
      other_rule = other_rules.max{|a, b| a.priority <=> b.priority}
      if other_rule
        # Swap the priorities. It's not possible to do arithmetic operations for this because there might be some deleted rules
        # that leave holes in a range of priorities. Though we could handle this on the scraping_rule DELETE, we shouldn't and don't.
        temp_priority = rule.priority
        rule.priority = other_rule.priority
        other_rule.priority = temp_priority
        rule.save
        other_rule.save
      else
        # There is no rule with a lower priority number. For cleanliness, let's make this rule the highest priority (lowest number).
        rule.priority = 0
        rule.save
      end
    end
    respond_to {|format| format.html { head :ok }}
  end

  def create    
    # Creates a new scraping rule.
    # There are four kinds of rules: continuous, binary, categorical, and intrinsic.
    # The first three kinds end up being specs bound to the product, e.g. ContSpec, 
    # while the last kind of rule inserts values directly into the product row.
    @scraping_rule = ScrapingRule.new(params[:scraping_rule])
    if ScrapingRule.find_all_by_product_type_and_local_featurename(ProductCategory.get_ancestors(Session.product_type), @scraping_rule.local_featurename).empty?
      @scraping_rule.product_type = Session.product_type
      # For priority, find all the scraping rules that share that local featurename (for that product type)
      potential_previous_scraping_rules = ScrapingRule.find_all_by_local_featurename_and_product_type(@scraping_rule.local_featurename, Session.product_type)
      # If there are any, get the highest priority and increment it for the new rule.
      # This gives all new rules a lower priority (lower priority number means higher priority).
      unless potential_previous_scraping_rules.empty?
        @scraping_rule.priority = (potential_previous_scraping_rules.map(&:priority).max + 1)
      end
      respond_to do |format|
        if @scraping_rule.save
          format.html { render text: "[REDIRECT]#{ product_type_scraping_rules_url(Session.product_type) }" }
        else
          format.html { head :bad_request }
        end
      end
    else
      # error
      respond_to do |format|
        format.html { head :bad_request }
      end
    end
  end
  
  def update
    succeeded = ScrapingRule.find(params[:id]).update_attributes(params[:scraping_rule].reject{|k,v|v.blank?})
    
    respond_to do |format|
      if succeeded
        format.html { render text: "[REDIRECT]#{ product_type_scraping_rules_url(Session.product_type) }" }
      else
        format.html { head :bad_request }
      end
    end
  end
  
  def show
    if request.referer =~ /full/
      #Results, so get all products
      products = Session.product_type_leaves.inject([]) do |res, leaf|
        res + BestBuyApi.category_ids(leaf)
      end
    else
      #Rules, so only show a few 
      leaves = Session.product_type_leaves
      products = leaves[0..9].inject([]) do |res, leaf|
        res + BestBuyApi.some_ids(leaf,[10/leaves.size,1].max)
      end
    end
    scraping_rules = Maybe(params[:id]).split('-')
    @colors = Hash[*scraping_rules.zip(%w(#4F3333 green blue purple pink yellow orange brown black)).flatten]
    if scraping_rules.length > 1
      #Check multirules
      candidates = scraping_rules.map{|sr| ScrapingRule.scrape(products,false,ScrapingRule.find(sr),nil,true)[:candidates]}.flatten
      @candidates = Candidate.multi(candidates)
    else
      #Check single rules
      @candidates = ScrapingRule.scrape(products,false,ScrapingRule.find(params[:id]),nil,true)[:candidates].sort{|a,b|(b.delinquent ? 2 : b.scraping_correction_id ? 1 : 0) <=> (a.delinquent ? 2 : a.scraping_correction_id ? 1 : 0)}
    end
    render :partial => 'candidate', :collection => @candidates, content_type: "text/html"
  end
  
  def destroy
    ScrapingCorrection.delete_all(["scraping_rule_id = ?",params[:id]])
    ScrapingRule.find(params[:id]).destroy
    render :nothing => true
  end
  
  private
  def covered(array)
    #Used to calculate feed coverage
    array.inject(0){|res,elem|elem.delinquent ? res : res+1}
  end
end

app/helpers/scraping_rules_helper.rb
module ScrapingRulesHelper
  # More thorough than getting the type of only one rule (though there should not be more than one type)
  def get_feature_type (rules)
    rule_types = rules.map{|rule| rule.rule_type}.uniq
    feature_type = ""
    rule_types.each do |rule_type|
      feature_type << rule_type << " "
    end
    feature_type
  end
end

app/views/scraping_rules/_candidate.html.erb
<div>
	<span class="bold"><%= candidate.sku %>&nbsp;</span><span href="#" class="expandable_sku" data-id="<%=candidate.sku%>">Fetch</span>&nbsp;&nbsp;&nbsp;
	Data: <span class="parsed bold" style="color: <%= candidate.scraping_correction ? "#B00C35" : (@colors.nil? ? "#4F3333" : @colors[candidate.scraping_rule_id.to_s] )%>" <%= "data-sc='#{candidate.scraping_correction_id}'" if candidate.scraping_correction %>><%= candidate.parsed %></span>&nbsp;&nbsp;
	&lt;=&nbsp;&nbsp; <span class="raw"<%= "data-rawhash='#{Digest::MD5.hexdigest(candidate.raw.to_s)}'" if candidate.raw.size > 20 %>><%= candidate.raw %></span>&nbsp;&nbsp;&nbsp;
	<% if candidate.scraping_correction #Is there a correction? %>
		<%= link_to "Update Correction", "#", :class => "correction" %>
		<%= link_to "Remove Correction", product_type_scraping_correction_path(Session.product_type, candidate.scraping_correction), :method => :delete %>
	<% else %>
		<%= link_to "Correction", "#", :class => "correction" %>
	<% end %>
</div>

app/views/scraping_rules/_form.html.erb
<fieldset>
  <legend><b>Parsing Rule</b></legend>
  <%= f.label :rule_type, "Type" %> 
  <div class="rule_type_button"><%= f.radio_button(:rule_type, "Continuous", :class => "required") %> Cont</div>
  <div class="rule_type_button"><%= f.radio_button(:rule_type, "Categorical", :class => "required") %> Cat</div>
  <div class="rule_type_button"><%= f.radio_button(:rule_type, "Binary", :class => "required") %> Bin</div>
  <div class="rule_type_button"><%= f.radio_button(:rule_type, "Text", :class => "required") %> Text</div>
  <%= f.label :remote_featurename, "Remote Feature" %> <%= f.text_field(:remote_featurename, :size => 35, :class => "required") %>
  <%= f.label :local_featurename, "Local Feature" %> <%= f.text_field(:local_featurename, :size => 35, :class => "required") %>
  <%= f.label :regex, "Regular Expression" %> 
  <div style="float: left;">
    <%= select "scraping_rule", "regex", ScrapingRule::REGEXES, {:include_blank=>false}, {:class=>"require regex scraping_rule_regex"} %>
    <input type="text" id="scraping_rule_regex_option" name="scraping_rule_option[regex]" class="require regexp scraping_rule_regex_option" style="display:none;"  value='<%= @scraping_rule.regex %>' />
    <br style="clear: both;" />
    <span style="float: left;">Custom Regex</span>
    <input type="checkbox" class="custom_regex" />
  </div>
  <%= f.label :min, "Min" %> <%= f.text_field(:min, :size => 35, :class => "ifcont") %>
  <%= f.label :max, "Max" %> <%= f.text_field(:max, :size => 35, :class => "ifcont") %>
  <%= f.label :valid_inputs, "Valid Inputs" %> <%= f.text_field(:valid_inputs, :size => 35) %>
  <% if @scraping_rule.rule_type == 'Categorical' %>
  <% end %>

  <% if @scraping_rule.rule_type == 'Categorical' %>
    <%= f.label :bilingual, "Bilingual" %>  
    <%= f.check_box(:bilingual) %>
  <% else %>
    <%= f.label :bilingual, "Bilingual", :style=>"display:none;" %>  
    <%= f.check_box(:bilingual, :style=>"display:none;") %>
  <% end %>

  <%= f.label :french, "French" %>
  <%= f.check_box(:french) %>
  <%= f.submit "Update Rule", :"data-id" => @scraping_rule.id, :class => "scraping_rule_submit", :style => "clear: left; margin-left: 200px" %>
  <p style="float: left; margin-bottom: 0">NB: Regular expressions can be either match or replace. To replace, use () with \1 \2 etc., with a "/" character in between the match and replace expressions. You can supply multiple regular expressions which are applied in order with the '^^' separator. The result will be the first match in the chain of regular expressions. If all fail, nothing is returned</p>
  <p style="float: left; margin-bottom: 0">For the valid inputs field use the '*' as a separator.</p>
</fieldset>

app/views/scraping_rules/create.html.erb
<p>Congratulations, you have created a rule.

app/views/scraping_rules/edit.html.erb
<%= form_for [Session.product_type, @scraping_rule], :url => product_type_scraping_rule_path, :remote => true, :html => { :class => "edit_scraping_rule" } do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/scraping_rules/index.html.erb
<h3 style="display: inline-block;" data-correctionsurl="<%= product_type_scraping_corrections_path %>">Rules</h3>
<div style="display: inline-block;">
  <%= form_for "/rules" do |f| %>
    <%= check_box_tag :coverage, 1, @coverage.present?, class: "coverage_submit" %> Coverage
  <% end %>
</div>
<% if @rules.empty? %>
  <div>
    <%= link_to "New Rule", "#", :class => "new_rule" %>
  </div>
<% end %>
<% @rules.each_pair do |local_feature,rules| %>
  <div style="margin-bottom: 1em; margin-left:10px;">
    <a href="#" class="togglable open mytitle">
      Feature: <span class="bold"><%= local_feature %></span>&nbsp;&nbsp;&nbsp;
      Type: <span class="bold"><%= get_feature_type(rules) %></span>&nbsp;&nbsp;&nbsp;
      <% if @coverage.present? %>
        Coverage: <span class="bold"><%= @coverage[local_feature] || @coverage[rules.first.id] %>/<%= @products_count %></span>
      <% end %>
    </a>
    <%= link_to "New Rule", "#", :class => "new_rule", :'data-lf' => local_feature %>
    <div class="contentholder">
      <%# Rules for this local_feature %>
      <% rules.each_with_index do |rule, remote_feature_counter| %>
        <div data-id="<%= rule.id %>">
          <%= link_to "#", :class => "raise_rule_priority", :title => "Raise rule priority" do %>&#8679;<% end if remote_feature_counter >= 1%>
          <a href="#" class="togglable closed fetch_candidates mytitle">
            Remote Feature: <span class="bold"><%= rule.remote_featurename %></span>&nbsp;&nbsp;&nbsp;
            <span style="color: <%= @colors[rule.id] if @colors %>">Rule:</span> <%= rule.regex %>&nbsp;&nbsp;&nbsp;
            <% if @coverage.present? %>
              Coverage: <span class="bold"><%= @coverage[rule.id] %>/<%= @products_count %></span>&nbsp;&nbsp;&nbsp;
            <% end %>
          </a>
          <%= link_to "Edit Rule", edit_product_type_scraping_rule_path(Session.product_type,rule), data: {id: rule.id}, :class => "edit_rule_dropdown" %>
          <%= link_to "Destroy", product_type_scraping_rule_path(Session.product_type, rule), :class => "delete_scraping_rule", :method => :delete, :remote => :true %>
          <div class="contentholder">Processing...</div>
        </div>
      <% end %>
      <% if @coverage.present? && rules.length > 1 #Multi-rules%>
        <div data-id="<%= rules.map(&:id).join("-") %>">
          <a href="#" class="togglable closed mytitle fetch_candidates">Applying All Rules</a>
          <div class="contentholder">Processing...</div>	
        </div>
      <% end %>
    </div>
    <%# End local_feature %>

	</div>
<% end %>

app/views/scraping_rules/new.html.erb
<h3>Create New Rule</h3>
<% if @raw %>
<h4>For key/value pair:</h4>
<div id="rule_creation_key_value_display">
    <%= @scraping_rule.remote_featurename %> : <%= @raw %>
</div>
<% end %>
<%= form_for [Session.product_type, @scraping_rule], :url => product_type_scraping_rules_path, :remote => true, :html => { :class => "edit_scraping_rule" } do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>