config/routes.rb
Firehose::Application.routes.draw do

  
  root :to => "b_bproducts#blank"

  resources :futureshop, only: [:index, :show], id: /\w+/i
  resources :bestbuy, only: [:index, :show], id: /\w+/i
  resources :accessories, only: [:index, :show], id: /\w+/i

  resources :product_types, path: "/", id: /[BFA]\w+/i, only: [:show] do
    resources :facets, only: [:index, :new, :create, :edit, :update], id: /\w+/, path: "layout_editor"
    resources :scraping_corrections, :except => [:show, :index], id: /\d+/
    resources :scraping_rules, id: /[\d-]+/
    resources :b_bproducts, only: [:index, :show], id: /\w+/
    resources :category_id_product_type_maps, only: [:new], :path=>"category_ids"
    match "category_ids" => "category_id_product_type_maps#show"
    match "scraping_rules/raisepriority" => "scraping_rules#raisepriority"
    match "/" => "b_bproducts#blank"
  end
  
  
end

app/models/scraping_correction.rb
class ScrapingCorrection < ActiveRecord::Base
  has_many :candidates
  belongs_to :scraping_rule
  
  validates :corrected,  :presence => true
  validates :scraping_rule_id, :presence => true
  validates :product_id, :presence => true
end

app/controllers/scraping_corrections_controller.rb
class ScrapingCorrectionsController < ApplicationController
  layout false
  # GET /scraping_corrections
  # GET /scraping_corrections.xml
  def index
    @scraping_corrections = ScrapingCorrection.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scraping_corrections }
    end
  end

  # GET /scraping_corrections/1
  # GET /scraping_corrections/1.xml
  def show
    @scraping_correction = ScrapingCorrection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scraping_correction }
    end
  end

  # GET /scraping_corrections/new
  # GET /scraping_corrections/new.xml
  def new
    @scraping_correction = ScrapingCorrection.new(params[:sc])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scraping_correction }
    end
  end

  # GET /scraping_corrections/1/edit
  def edit
    @scraping_correction = ScrapingCorrection.find(params[:id])
  end

  # POST /scraping_corrections
  # POST /scraping_corrections.xml
  def create
    @scraping_correction = ScrapingCorrection.new(params[:scraping_correction])

    respond_to do |format|
      if @scraping_correction.save
        format.html { head :ok }
        format.xml  { render :xml => @scraping_correction, :status => :created, :location => @scraping_correction }
      else
        format.html { head :bad_request }
        format.xml  { render :xml => @scraping_correction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scraping_corrections/1
  # PUT /scraping_corrections/1.xml
  def update
    @scraping_correction = ScrapingCorrection.find(params[:id])

    respond_to do |format|
      if @scraping_correction.update_attributes(params[:scraping_correction])
        format.html { head :ok }
        format.xml  { head :ok }
      else
        format.html { head :bad_request }
        format.xml  { render :xml => @scraping_correction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scraping_corrections/1
  # DELETE /scraping_corrections/1.xml
  def destroy
    @scraping_correction = ScrapingCorrection.find(params[:id])
    @scraping_correction.destroy

    respond_to do |format|
      format.html { head :ok }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scraping_corrections_helper.rb
module ScrapingCorrectionsHelper
end

app/views/scraping_corrections/_form.html.erb
<%= form_for [Session.product_type, @scraping_correction], :url => (@scraping_correction.id.nil? ? product_type_scraping_corrections_path : product_type_scraping_correction_path) do |f| %>
  <%= f.text_field :corrected, :size => 8, :class => "correction_field" %> <%= f.hidden_field :product_id %> <%= f.hidden_field :raw %> <%= f.hidden_field :scraping_rule_id %>
<%= f.submit "Correct", :class => "correction_submit" %>
<% end %>

app/views/scraping_corrections/index.html.erb
<h1>Listing scraping_corrections</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Product type</th>
    <th>Corrected</th>
    <th>Remote featurename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scraping_corrections.each do |scraping_correction| %>
  <tr>
    <td><%= scraping_correction.product_id %></td>
    <td><%= scraping_correction.product_type %></td>
    <td><%= scraping_correction.corrected %></td>
    <td><%= scraping_correction.remote_featurename %></td>
    <td><%= link_to 'Show', scraping_correction %></td>
    <td><%= link_to 'Edit', edit_scraping_correction_path(scraping_correction) %></td>
    <td><%= link_to 'Destroy', scraping_correction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scraping correction', new_scraping_correction_path %>

app/views/scraping_corrections/new.html.erb
<%= render 'form' %>

app/views/scraping_corrections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @scraping_correction.product_id %>
</p>

<p>
  <b>Product type:</b>
  <%= @scraping_correction.product_type %>
</p>

<p>
  <b>Raw:</b>
  <%= @scraping_correction.raw %>
</p>

<p>
  <b>Corrected:</b>
  <%= @scraping_correction.corrected %>
</p>

<p>
  <b>Remote featurename:</b>
  <%= @scraping_correction.remote_featurename %>
</p>


<%= link_to 'Edit', edit_scraping_correction_path(@scraping_correction) %> |
<%= link_to 'Back', scraping_corrections_path %>