config/routes.rb
Firehose::Application.routes.draw do

  
  root :to => "b_bproducts#blank"

  resources :futureshop, only: [:index, :show], id: /\w+/i
  resources :bestbuy, only: [:index, :show], id: /\w+/i
  resources :accessories, only: [:index, :show], id: /\w+/i

  resources :product_types, path: "/", id: /[BFA]\w+/i, only: [:show] do
    resources :facets, only: [:index, :new, :create, :edit, :update], id: /\w+/, path: "layout_editor"
    resources :scraping_corrections, :except => [:show, :index], id: /\d+/
    resources :scraping_rules, id: /[\d-]+/
    resources :b_bproducts, only: [:index, :show], id: /\w+/
    resources :category_id_product_type_maps, only: [:new], :path=>"category_ids"
    match "category_ids" => "category_id_product_type_maps#show"
    match "scraping_rules/raisepriority" => "scraping_rules#raisepriority"
    match "/" => "b_bproducts#blank"
  end
  
  
end

app/controllers/futureshop_controller.rb
class FutureshopController < AccessoriesController
  def index
    @no_header = true
    initialize_constants()
    # Laptops: F1002, Tablets: F29958, TVs: Ftvs, Fridges: F1953, Cameras: F1127, DSLRs: F22553
    product_types = ["F1002","F29958","Ftvs","F1953","F1127","F23773"]
    ids = get_products(product_types)
    render "landing", :locals => {:best_sellers => ids}
  end
  
  def show
    @no_header = true
    initialize_constants()
    # The bestsellers do not have a count (accessories do...)
    if params.has_key?(:count)
      count = params[:count]
    else
      count = "-"
    end
    # Check if request is for a product type or a product
    if params[:id] =~ /^[BF]/ # if product type
      ids = get_products([params[:id]])
      unless count == "-"
        params[:prod_acc_cats][params[:sku]] = [params[:acc_cat],params[:count]]
        render "show", :locals => {:cat_prods => ids, :prod_acc_cats => params[:prod_acc_cats], :count => count}
      else
        prod_acc_cats = {}
        ids.each_pair do |category,products|
          products.each do |product|
            prod_acc_cats[product.sku] = [params[:acc_cat],"-"]
          end
        end
        render "show", :locals => {:cat_prods => ids, :prod_acc_cats => prod_acc_cats, :count => count}
      end
    else  # if product
      render "show_single", :locals => {:product => get_product(params[:id]).first, :cat => params[:cat], :acc_cat => params[:acc_cat], :count => count}
    end
  end
end

app/views/futureshop/_accessory.html.erb
<div class="accessory"; style="position:relative; display:inline-block; height: 95px; margin-top:3px; margin-right:15px">
  <span class="num"><%= accessory.count %></span>
  <% # require "open-uri"
		#  begin
		# 	open("http://www.bestbuy.ca/multimedia/Products/150x150/#{accessory.first[0..2]}/#{accessory.first[0..4]}/#{accessory.first}.jpg")
		#  rescue OpenURI::HTTPError
		#  	image_url =  "http://www.y-hhh.com.cn/yashige%20en/haitian/pic/NO_PIC.jpg" 
		#  else
		#  	image_url = "http://www.bestbuy.ca/multimedia/Products/150x150/#{accessory.first[0..2]}/#{accessory.first[0..4]}/#{accessory.first}.jpg"
		#  end
		  #sku = get_sku(accessory.value)
		%>
	<%= image_tag accessory.img_url, class: "productimg", title: "Recommended", alt: "Accessory" %>
	<div class="sku"><%= accessory.sku %></div>
</div>

app/views/futureshop/_featured.html.erb
<div class="featured">
	<table>
		<tr>
			<td class="bestseller">
			  <div class="product">
			    <span class="num" style="background-color:#66FFFF"><%= featured.store_sales.to_i %></span>
					<%= image_tag featured.img_url, :class => "productimg", title: "SKU:#{featured.sku}" %> 	
					<div class="title">		

        	  <%= link_to featured.name, futureshop_path(featured.id,:cat => cat), {:class => "link", :style =>"color:black;"} %>
  				</div>
				</div>
			</td>
			<td class="sorting">
			  <div style="margin-bottom:2px;top:0;">Accessory Categories:</div>
			  <% total = featured.total_acc_sales %>
			  <%= link_to "Top #{@accessories_per_product_type} (#{total})", futureshop_path(cat, :sku => featured.sku, :prod_acc_cats => prod_acc_cats, :acc_cat => "Top #{@accessories_per_product_type}", :count => total), {:class => "link"} %>
			  <br>
			  <%= link_to "Top #{@accessories_per_product_type}: Limited (#{total})", futureshop_path(cat, :sku => featured.sku, :prod_acc_cats => prod_acc_cats, :acc_cat => "Top #{@accessories_per_product_type}: Limited", :count => total), {:class => "link"} %>
			  <br>
			  <% get_cats_and_counts(featured).each do |acc_cats|%>
			    <%= link_to t(acc_cats.value+".name")+"  (#{acc_cats.count})", futureshop_path(cat, :sku => featured.sku, :prod_acc_cats => prod_acc_cats, :acc_cat => acc_cats.value, :count => acc_cats.count), {:class => "link"} %>
			    <br>
			  <% end %>  
			</td>
			<td class="accessories" style="width:1000px;">
		    <div style="margin-bottom:2px;">Recommended Accessories:</div>
        <% acc = get_select_accessories(featured, prod_acc_cats[featured.sku][0], prod_acc_cats[featured.sku][1]) %>
          <% acc.each_pair do |title,data| %>
            <div class="cat_name"><%= title+"  (#{data[0]})"%></div>
            <%= render partial: "accessory", collection: data[1] %>
            <br><br>
          <% end %>
		  </td>
		</tr>
	</table>	

</div>

app/views/futureshop/_featured_list.html.erb
<div class="first_featured">
  <span class="num" style="background-color:#66FFFF"><%= featured_list.store_sales.to_i %></span>
    <%= image_tag featured_list.img_url, class: "productimg", title: "Product", alt: "#{featured_list.sku}"%>
    <div style="text-align:center;">
      <%= link_to featured_list.name, futureshop_path(featured_list.id,:cat => cat), {:class => "link"} %>
    </div>  
</div>

app/views/futureshop/_product.html.erb
<div class="single_product">
	<table>
		<tr>
			<td class="bestseller">
			  <div class="product">
			    <span class="num" style="background-color:#66FFFF"><%= product.store_sales.to_i %></span>
					<%= image_tag product.img_url, :class => "productimg", title: "SKU:#{product.sku}" %> 	
					<div class="title">		
  					<%= "#{product.sku}" %>
  				</div>
				</div>
			</td>
			<td class="accessories" style="width:1000px;">
		    <div style="margin-bottom:2px;">Recommended Accessories:</div>
        <% acc = get_accessories(product)%>
	      <% acc.each_pair do |title,data| %>
		      <div class="cat_name"><%= title+"(#{data[0]})"%></div>
		      <%= render partial: "accessory", collection: data[1] %>
		      <br><br>
		    <% end %>
		  </td>
		</tr>
	</table>	

</div>

app/views/futureshop/index.html.erb
<div>
  <div class="retailer">
    <a href="/bestbuy">BestBuy</a> | <a href="/futureshop">FutureShop</a>
  </div>
<br>
<h2 class="heading">Best Selling Products</h2>
<% best_sellers.each_pair do |category,products| %>
  <h4 style="margin-left:20px; margin-bottom:3px;">
    <%= link_to t(category+".name"), futureshop_path(category, :acc_cat => "Top #{@accessories_per_product_type}"), {:class => "link"} %>
  </h4>
  <div class="category">
    <%= render partial: "featured_list", collection: products, :locals => {:cat => category}%>
  </div>
<% end %>
</div>

app/views/futureshop/landing.html.erb
<div style="font-family:arial">
<h2>Recommended Accessories</h2>
  <h4 style="text-align:center; margin-top:40px;">Enter a product Id</h4>
  <div style="text-align:center;"> <%= text_field_tag :sku_search, "", class: "sku_search" %>
      <button id="enter_sku_search">Enter</button>

    <h4 style="text-align:center; margin-top:50px;" >Examples</h4>
    <button id="ipad_Fsearch">iPad</button>
    <button id="blackberry_Fsearch">Blackberry</button>
    <button id="dslr_Fsearch">DSLR</button>
  </div>
</div>

app/views/futureshop/show.html.erb
<div style="font-family:arial">
<h2>Top Purchases</h2>
<h4 style="margin-left:20px;"><%= link_to "All Best-Selling Products", futureshop_index_path %></h4>
  <% cat_prods.each_pair do |category,products|%>
		<h4 style="margin-left:20px; margin-bottom:3px;"><%= t(category+".name") %></h4>
		<div class="category">
			<%= render partial: "featured", collection: products , locals: {:cat => category, :prod_acc_cats => prod_acc_cats, :count => count} %>
		</div>
<% end %>
</div>

app/views/futureshop/show_single.html.erb
<div style="font-family:arial">
<h2 class="heading"><%= product.cat_specs.find_by_name("title").try(:value) %></h2>
<h4 style="margin-left:20px;"><%= link_to "All Best-Selling Products", futureshop_index_path %></h4>
	<h4 style="margin-left:20px; margin-bottom:3px;"><%= product.cat_specs.find_by_name("title").try(:value) %></h4>
	<div class="category"  style="width: 624px; overflow: hidden;">
		<%= render partial: "product", :locals => {:product => product} %>
	</div>
</div>